# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f2d81ed99e96ea31ee0edbbe26115ddbad182e0a852270f6cd8a206b621f1cf96d56a1c4a5bd1a9bb1690e199547dfad819dcfc6c13d79505b6146ce6954d35

test:
  secret_key_base: 306efd314b326979c4e66fbf93fc198e2018c287816d02e6557b23b278256f7ee2d749aff3d3cc255fa00ced43b3878d574ac359da666002b2fd39c21963218b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
